// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRJZzGPm5eh5Tmpl0yI7X-RG1l9yZxSuA',
    appId: '1:363528210172:web:4bbf1d81a6fb03b0313979',
    messagingSenderId: '363528210172',
    projectId: 'chatapp-d0f34',
    authDomain: 'chatapp-d0f34.firebaseapp.com',
    storageBucket: 'chatapp-d0f34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjt2wpzd5stTqLYNCz2uGak9YhtJgCWY',
    appId: '1:363528210172:android:693de9f648ee66f8313979',
    messagingSenderId: '363528210172',
    projectId: 'chatapp-d0f34',
    storageBucket: 'chatapp-d0f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHno6QKKZ9Pj0flfm-jCHIUw5U5-QgZjw',
    appId: '1:363528210172:ios:422c7cb7878ea886313979',
    messagingSenderId: '363528210172',
    projectId: 'chatapp-d0f34',
    storageBucket: 'chatapp-d0f34.appspot.com',
    iosBundleId: 'com.example.whatsappChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHno6QKKZ9Pj0flfm-jCHIUw5U5-QgZjw',
    appId: '1:363528210172:ios:422c7cb7878ea886313979',
    messagingSenderId: '363528210172',
    projectId: 'chatapp-d0f34',
    storageBucket: 'chatapp-d0f34.appspot.com',
    iosBundleId: 'com.example.whatsappChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRJZzGPm5eh5Tmpl0yI7X-RG1l9yZxSuA',
    appId: '1:363528210172:web:779fbc713a951d8f313979',
    messagingSenderId: '363528210172',
    projectId: 'chatapp-d0f34',
    authDomain: 'chatapp-d0f34.firebaseapp.com',
    storageBucket: 'chatapp-d0f34.appspot.com',
  );
}
